language: node_js
# nodejs version
node_js: 
    - '10.14.1'

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install -g vuepress

before_script:
  - git clone -b gh-pages "https://${GH_TOKEN}@${GH_REF}" vuepress
  - rm ./vuepress/* -fr

# build
script:
  - cd ./docs
  - vuepress build

after_script:
  - cd ./vuepress
  - git add --all .
  - git commit -m "Update docs."
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

branches:
  only:
    - master
env:
 global:
